# Labeler configuration
# See: https://github.com/actions/labeler
# Labels must match those defined in .github/maintenance/labels.sh

# Documentation
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

# CI/CD
area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

# Configuration
area/config:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.config.*"
          - "**/tsconfig*.json"
          - "**/vite.config.*"
          - "**/.env*"
          - "!.github/**/*"

# Dependencies
area/deps:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"
          - "pnpm-lock.yaml"
          - "yarn.lock"

# Testing
area/testing:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.test.*"
          - "**/*.spec.*"
          - "**/tests/**/*"
          - "**/__tests__/**/*"
          - "**/vitest.config.*"
          - "**/jest.config.*"

# UI Components
area/ui:
  - changed-files:
      - any-glob-to-any-file:
          - "**/components/**/*"
          - "**/ui/**/*"

# User Experience
area/ux:
  - changed-files:
      - any-glob-to-any-file:
          - "**/hooks/**/*"
          - "**/stores/**/*"
          - "**/context/**/*"

# Accessibility
area/a11y:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.a11y.*"
          - "**/accessibility/**/*"

# API/Data
area/api:
  - changed-files:
      - any-glob-to-any-file:
          - "**/api/**/*"
          - "**/services/**/*"
          - "**/queries/**/*"

# Authentication
area/auth:
  - changed-files:
      - any-glob-to-any-file:
          - "**/auth/**/*"
          - "**/authentication/**/*"
