# Documentation
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

# CI/CD
area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

# Docker
area/docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Dockerfile*"
          - "**/.dockerignore"
          - "**/docker-compose*.yml"
          - "**/docker-compose*.yaml"

# Configuration
area/config:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.config.*"
          - "**/tsconfig*.json"
          - "**/vite.config.*"
          - "**/.env*"
          - "!.github/**/*"

# Dependencies
area/deps:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"
          - "pnpm-lock.yaml"
          - "yarn.lock"

# Testing
area/testing:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.test.*"
          - "**/*.spec.*"
          - "**/tests/**/*"
          - "**/__tests__/**/*"
          - "**/vitest.config.*"
          - "**/jest.config.*"

# UI Components
area/ui:
  - changed-files:
      - any-glob-to-any-file:
          - "**/components/**/*"
          - "**/ui/**/*"

# User Experience
area/ux:
  - changed-files:
      - any-glob-to-any-file:
          - "**/hooks/**/*"
          - "**/stores/**/*"
          - "**/context/**/*"

# Accessibility
area/a11y:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.a11y.*"
          - "**/accessibility/**/*"

# Styles
area/styles:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.css"
          - "**/*.scss"
          - "**/*.sass"
          - "**/*.less"
          - "**/tailwind.config.*"

# API/Data
area/api:
  - changed-files:
      - any-glob-to-any-file:
          - "**/api/**/*"
          - "**/services/**/*"
          - "**/queries/**/*"

# Repository label
repo/dashboard:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*"
