# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        # Coverage is informational only - don't block PRs
        informational: true
        target: auto
        threshold: 5%
    patch:
      default:
        # Coverage is informational only - don't block PRs
        informational: true
        target: auto
        threshold: 5%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: true

ignore:
  - "node_modules/**"
  - "dist/**"
  - "coverage/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "*.config.js"
  - "*.config.ts"
  - "vite.config.ts"
  - "eslint.config.js"
